font_family      monospace
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14.0

scrollback_lines 10000
copy_on_select yes
enable_audio_bell no
opacity 0.9

# native tabs, since that's the point of trying kitty over alacritty+zellij
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
